"""algo cool

Revision ID: c269606bc130
Revises: 
Create Date: 2024-04-10 03:25:11.156678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c269606bc130'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Boolean(create_constraint=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediccion')
    # ### end Alembic commands ###
