name: Continuous Delivery to Azure Container Registry and Web App

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_push_container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: regabichallenge.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image to Azure Container Registry
      run: |
        docker build -t regabichallenge.azurecr.io/flask_container:latest .
        docker push regabichallenge.azurecr.io/flask_container:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: 'regabichallenge.azurecr.io/flask_container:latest'
