name: Continuous Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_model:
    name: Train ML Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0  # Update to use a version compatible with Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v2.4.0  # Update to use a version compatible with Node.js 20
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py
          
      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: model.pkl
