name: Continuous Training Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature1
      - feature2
  pull_request:
    branches:
      - main
      - develop
      - feature1
      - feature2

jobs:
  train_model:
    name: Train ML Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use latest version
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python model.py
          
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl
